### ISSUE TITLE
No working (Tested on web)

### ISSUE THREAD

**Issue by AbdallahR99** [RounakTadvi/internet_connection_checker#1]
Always return 

> No internet :( Reason:
> [AddressCheckResult(AddressCheckOptions(Instance of 'InternetAddress', 53, 0:00:10.000000), false), AddressCheckResult(AddressCheckOptions(Instance of 'InternetAddress', 53, 0:00:10.000000), false), AddressCheckResult(AddressCheckOptions(Instance of 'InternetAddress', 53, 0:00:10.000000), false)]

**Comment by RounakTadvi** [comment]
Good Catch, I'll look into it.

**Comment by rajeshzmoke** [comment]
this package does not work on web. is there a workaround to check internet connection in web?

**Comment by jasco** [comment]
My observation is that in web the host unreachable is being cause by `Socket._connection` throwing `UnimplementedError`.   In contrast, desktop is ok.

**Comment by mahendary** [comment]
This doesn't work on web for me as well. any fix for this?

**Comment by RounakTadvi** [comment]
In order to retrieve information about the quality/speed of a browser's connection, the web implementation of the connectivity plugin uses the browser's [NetworkInformation Web API](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation), which as of this writing (June 2020) is still "experimental", and not available in all browsers

**Comment by OutdatedGuy** [comment]
Looks like this package is not actively maintained. So I just created a [temporary workaround](https://pub.dev/packages/internet_connection_checker_plus) of this package.

It doesn't have many functionalities that the original package have though.

**Comment by RounakTadvi** [comment]
Checkout the latest version of the package, it supports web platform.

Checkout the below demo video:
https://github.com/user-attachments/assets/f5119886-93f4-4279-8cbc-bd8ae19731c9
