### ISSUE TITLE
Modify testing logic to immediately return if any of the simultaneous pings succeed

### ISSUE THREAD

**Issue by MrCsabaToth** [RounakTadvi/internet_connection_checker#12]
Currently the logic is "All addresses are pinged simultaneously. ... When all the requests complete with either success or failure, a check is made to see if the list contains at least one true boolean.". However if any of the hosts slow to respond (for example for some reason CloudFlare DNSes don't respond (https://github.com/komapeb/data_connection_checker/issues/10#issuecomment-736704451) then we have to wait a timeout (10 seconds, which is excruciating for a user, given that some pings may have already succeeded). In my opinion if any of the pings succeed then the test could already cut short any other pings and return immediately.

**Comment by madatr** [comment]
is this online?

**Comment by MrCsabaToth** [comment]
> is this online?

Unfortunately not, the PR is just sitting there. I'm waiting as well because I don't like to rely on my own fork (but that's what I do right now).

**Comment by MrCsabaToth** [comment]
@RounakTadvi are you here?

**Comment by abdimussa87** [comment]
Any updates?

**Comment by RounakTadvi** [comment]
Yes, it's available on pub.dev

**Comment by abdimussa87** [comment]
Thank you

**Comment by abdimussa87** [comment]
@MrCsabaToth Thank you

**Comment by abdimussa87** [comment]
@RounakTadvi How can we change the interval where the checking for internet connection happens from 10 seconds to 5 second or so?

**Comment by MrCsabaToth** [comment]
> How can we change the interval where the checking for internet connection happens from 10 seconds to 5 second or so?

@abdimussa87 Can you open a StackOverflow question and link it here? I'll answer there.
