### ISSUE TITLE
Edit defaults

### ISSUE THREAD

**Issue by adri195** [RounakTadvi/internet_connection_checker#18]
I have been testing the package and I think it would be interesting to allow editing of the default values.
The main problem I found is that I have to keep the user waiting 10 seconds to notify them that they have no internet. It would be very useful to be able to edit this default value

**Comment by RounakTadvi** [comment]
I'll add it in the next release @adri195

**Comment by rakesh0689** [comment]
Is there any update on editing the default values like timeout, address etc?

**Comment by hosajadi** [comment]
if you want to set a timeout letter than 10 seconds you can set it by yourself, something like this:
`try {
      bool result = await InternetConnectionChecker().hasConnection.timeout(Duration(seconds: 5));
      return result;
    }catch (e) {
      return false;
    }`

**Comment by RounakTadvi** [comment]
@rakesh0689 The update on editing the default values like timeout, address is available now in the latest version of the plugin
