### ISSUE TITLE
hasConnection return false even there is Mobile connection

### ISSUE THREAD

**Issue by golanitay1984** [RounakTadvi/internet_connection_checker#22]
Hi, 

I am facing the opposite of issue #6 

I am using a physical device (Galaxy S22 Ultra).
The device is connected to a WiFi camera via Wi-Fi (without an internet connection, of course) and also to Mobile data.

In the following line:
`bool result = await InternetConnectionChecker().hasConnection;`
I received "false" even I am connecting to the Mobile data.

Thanks

**Comment by Stratovarius93** [comment]
I have same bug. Any solution?

**Comment by fbernaly** [comment]
I have the same issue, it is returning false even there is internet connection, I am using `internet_connection_checker: ^0.0.1+3` and have tested with iOS and Android.

**Comment by rafiiAP** [comment]
same problem!

**Comment by tokumaci** [comment]
Same problem !!

**Comment by RounakTadvi** [comment]
@golanitay1984 Kindly use the latest version of the package, it does not relies on Socket anymore. Since this issue has been inactive for a while, I’ll be closing it now. If the problem persists, please file a new issue.
