### ISSUE TITLE
hasConnection return false for some internet provider

### ISSUE THREAD

**Issue by eggysudianto** [RounakTadvi/internet_connection_checker#24]
Hi, I from Indonesia and I tried this lib is working normal until I found error always return false for 1 internet provider the name is "tri"(https://tri.co.id/), even there is mobile connection (can browsing, chat, etc). thanks

**Comment by Nicomnr02** [comment]
Mas udah solved kah?

**Comment by irwancheung** [comment]
> Mas udah solved kah?

Same problem to me. I solved it by using VPN.

**Comment by irwancheung** [comment]
Same problem. It only works with VPN if using Tri provider.

**Comment by irwancheung** [comment]
Problem still persists with Tri provider. I solved it by changing the addresses.

`InternetConnectionChecker().addresses = [
      AddressCheckOptions(hostname: 'google.com', port: 80),
];
`

**Comment by RounakTadvi** [comment]
@eggysudianto The latest version of the package does not relies on Socket anymore, kindly use the latest version of the package. Since this issue has been inactive for a while, I’ll be closing it now. If the problem persists, please file a new issue.
