### ISSUE TITLE
SocketException (SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = 2620:0:ccc::2, port = 53

### ISSUE THREAD

**Issue by Rodrigossff91** [RounakTadvi/internet_connection_checker#26]
Shows this error.. has anyone gone through this 

static final InternetConnectionChecker _instance =
      InternetConnectionChecker.createInstance();

  /// Ping a single address. See [AddressCheckOptions] for
  /// info on the accepted argument.
  Future<AddressCheckResult> isHostReachable(
    AddressCheckOptions options,
  ) async {
    Socket? sock;
    try {
      sock = await Socket.connect(

**Comment by nativeaditya** [comment]
same exception

**Comment by robkawaev** [comment]
same

**Comment by OmarzSelim** [comment]
Same 

> Shows this error.. has anyone gone through this
> 
> static final InternetConnectionChecker _instance = InternetConnectionChecker.createInstance();
> 
> /// Ping a single address. See [AddressCheckOptions] for /// info on the accepted argument. Future isHostReachable( AddressCheckOptions options, ) async { Socket? sock; try { sock = await Socket.connect(

Have you managed to fix it ?

**Comment by RounakTadvi** [comment]
@robkawaev Kindly use the latest version of the package, it does not relies on Socket anymore.Since this issue has been inactive for a while, I’ll be closing it now. If the problem persists, please file a new issue.
