### ISSUE TITLE
hasConnection return  true even without any bandwith on mobile

### ISSUE THREAD

**Issue by markarik** [RounakTadvi/internet_connection_checker#27]
When connected to wifi, hasConnection is working accordingly by when on Mobile connection , the hasConnection is always giving a true

**Comment by MunibullahShah** [comment]
Same issue

**Comment by dev-RodrigoLopez** [comment]
Same issue

**Comment by RounakTadvi** [comment]
@markarik Kindly try the latest version of the package it does not relies on Socket anymore. Since this issue has been inactive for a while, I’ll be closing it now. If the problem persists, please file a new issue.
