### ISSUE TITLE
Monitor internet connection (slow or fast)

### ISSUE THREAD

**Issue by deeeznuds** [RounakTadvi/internet_connection_checker#32]
Hi!
I really liked this plugin for its versatility.
I'm missing functionality that I can't find anywhere else, I want to be alerted if the internet speed is too slow, warning users that the request might be taking longer than usual.
According to the implementation, I see it like this: you need to measure the speed of making attempts for the presence of the Internet connection, then calculate the average speed and compare it with the reference time.
Please consider my suggestion, thanks!

**Comment by Rana-Yehya** [comment]
Hello, have you found any variable that can be used in the plugin to be used?

**Comment by RounakTadvi** [comment]
This is a good feature that can be added which provides info about the speed of the internet.

**Comment by RounakTadvi** [comment]
@deeeznuds The feature has been implemented in the latest version, kindly check out the example folder to check out the latest examples.
