### ISSUE TITLE
always return false in release mode

### ISSUE THREAD

**Issue by Muhammad-Rehab** [RounakTadvi/internet_connection_checker#33]
Hello,
The method internetConnectionChecker.hasConnection works correctly in debug mode but always returns false in release mode or when I build apk release although my mobile is connected to the wifi

**Comment by cnrblm** [comment]
Did you add internet permission to Android manifest?

**Comment by mregnauld** [comment]
Adding the following in the Android manifest solved the issue for me:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    
    <application
        ...
```

**Comment by RounakTadvi** [comment]
Try the latest version of the package it will resolve your issue.

**Comment by RounakTadvi** [comment]
Closing this since updating the manifest file with the correct permissions resolves this particular issue.

<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    
    <application
        ...
