### ISSUE TITLE
I have a modem without internet but the Hasconnection returns True

### ISSUE THREAD

**Issue by dev-RodrigoLopez** [RounakTadvi/internet_connection_checker#34]
The same for mobile data without megabytes returns TRUE

**Comment by victort21** [comment]
I went through the same problem and the best solution I found is to make an http request to https://google.com and check the status if it is 200 the user has a connection if not he does not have. Example below
`Future<bool> checkInternetConection() async {
  bool result = await InternetConnectionChecker().hasConnection;
  return result;
}
Future<bool> pingToGoogle() async {
  final dio = Dio();
  final hasInternet = await checkInternetConection();
  if(hasInternet) {
    final response = await dio.get('https://google.com');
    return response.statusCode == 200;
  }
  return false;
}`

**Comment by RounakTadvi** [comment]
@dev-RodrigoLopez Kindly use the latest version of the package earlier version relied on Socket. Since this issue has been inactive for a while, I’ll be closing it now. If the problem persists, please file a new issue.
