### ISSUE TITLE
Same internet connection event status is emitted multiple times consecutively for every change in the connection status 

### ISSUE THREAD

**Issue by pratheshsanth** [RounakTadvi/internet_connection_checker#35]
We use InternetConnectionChecker to listen for the network status change(i.e., connected or disconnected) in one of our mobile app. And for every connection status change(from connected to disconnected or disconnected to connected), same status events are fired multiple times.
For example if the status changes from disconnected to connected in the mobile phone, connected status is emitted multiple times consecutively in the listener. 
Kindly request to help fix this issue.
InternetConnectionChecker().onStatusChange.listen((status){
        switch (status) {
          case InternetConnectionStatus.connected:
            log('network connected');
            break;
          case InternetConnectionStatus.disconnected:
            log(' network disconnected');
            break;
        }
      }
    });

**Comment by RounakTadvi** [comment]
@pratheshsanth This has been taken into consideration and the fix is available in the latest release of the package.

**Comment by shahmirzali49** [comment]
the same issue. I'm using `internet_connection_checker: ^3.0.1`

**Comment by shahmirzali49** [comment]
_connectivityChecker.onStatusChange.listen((status) {
      print("Connection status: $status");
    });
