### ISSUE TITLE
What is the difference with "data_connection_checker" plugin ?

### ISSUE THREAD

**Issue by mayouf** [RounakTadvi/internet_connection_checker#4]
Hi,
this packages seems similar to the one below, right ?

https://pub.dev/packages/data_connection_checker

**Comment by RounakTadvi** [comment]
It is, the data_connection_checker package maintainer isn't active for a while because of which internet_connection_checker is published with sound null safety

**Comment by mayouf** [comment]
OK, I think I should thank you then...

I been building my app to be internet sensitive...I provided a cubit on above MaterialApp like it should be.

BUT I WAS USING data_connection_checker plugin !!!!    

And I tried to use BlocListener to listen on status change from connection.....nothing !!    WEIRD !!!

No error log to use for debug....very strange, a total NOTHING.

I spent quite a time....I tried to use your plugin.....AND BIM....

For some reason, it worked !  And I tried back to use the old plugin, it did not work again....

So thanks for this plugin....you saved my day !! 

### **WARNING :**  
SO PEOPLE HERE,

DO  NOT USE **[data_connection_checker](https://pub.dev/packages/data_connection_checker)** ANYMORE 

USE  **[internet_connection_checker](https://pub.dev/packages/internet_connection_checker)**

**Comment by RounakTadvi** [comment]
Thank you for your kind words 😃
