### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by Jakoo13** [RounakTadvi/internet_connection_checker#40]
I'm not seeing any updates to this Repo in many months. Is there a different repo available that is being properly maintained?

**Comment by anatoliisudor** [comment]
I had a same question, but 16 month for an update looks like a lot. Decided to switch to [https://pub.dev/packages/connecteo](https://pub.dev/packages/connecteo)

**Comment by 0xmarkhernandez** [comment]
> I had a same question, but 16 month for an update looks like a lot. Decided to switch to https://pub.dev/packages/connecteo

@anatoliisudor, how's the performance of [connecteo](https://pub.dev/packages/connecteo)?

**Comment by RounakTadvi** [comment]
An update will be released tomorrow, I can understand there's a lot of inactivity but rest assured I look forward to actively maintain this repository

**Comment by 0xmarkhernandez** [comment]
> An update will be released tomorrow, I can understand there's a lot of inactivity but rest assured I look forward to actively maintain this repository.

Thanks @RounakTadvi 🙌🏻 , I will help on the testing part and send feedback. 💪🏻

**Comment by RounakTadvi** [comment]
@0xmarkhernandez Check the new branch for testing and feedback

**Comment by RounakTadvi** [comment]
@Jakoo13 @0xmarkhernandez @anatoliisudor I have released a new version of the package.
