### ISSUE TITLE
fix: 1.1.1.1 - blocked CORS policy?

### ISSUE THREAD

**Issue by ibiolm** [RounakTadvi/internet_connection_checker#46]
It seems 1.1.1.1 has changed their CORS policy. Using this for a Flutter Web app and in Chrome browser I get the following error messages:

**Access to XMLHttpRequest at 'https://1.1.1.1/' from origin '.......................' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.Understand this error main.dart.js:101354** 
        
I am running a singleton check periodically.

Maybe this IP should be removed from the check list?

Thanks

**Comment by RounakTadvi** [comment]
Thanks for raising this issue, I'll look into it.

**Comment by ibiolm** [comment]
Thanks. Good alternative is maybe 'api.github.com'

Unless you specifically chose an IP address which does not need be resolved and so bypass a possible broken DNS server.

**Comment by RounakTadvi** [comment]
@ibiolm Kindly use the latest version of the package, https://1.1.1.1 has been removed from the latest version and the following urls are added:

'https://dummyapi.online/api/movies/1'
'https://jsonplaceholder.typicode.com/albums/1'
'https://fakestoreapi.com/products/1'
