### ISSUE TITLE
Trying to install the package

### ISSUE THREAD

**Issue by ghost** [RounakTadvi/internet_connection_checker#7]
I tried to install the package in my app. And when I saved the pubspec.yml file in visual studio code, an error message appeared in my terminal:-

> Because every version of internet_connection_checker depends on universal_io ^2.0.0 which depends on crypto ^3.0.0, every version of internet_connection_checker requires crypto ^3.0.0.
> 
> (1) So, because basic_utils >=2.6.1 <3.0.0-nullsafety.0 depends on crypto ^2.1.5, internet_connection_checker is incompatible with basic_utils >=2.6.1 <3.0.0-nullsafety.0.
> 
> Because no versions of validators match >2.0.1 <3.0.0 and validators 2.0.1 depends on vin_decoder ^0.1.2, validators ^2.0.1 requires vin_decoder ^0.1.2.
> 
> And because no versions of vin_decoder match >0.1.3 <0.2.0 and vin_decoder >=0.1.2 <0.1.3 depends on basic_utils ^2.5.4, validators ^2.0.1 requires basic_utils ^2.5.4 or vin_decoder 0.1.3.
> 
> And because basic_utils >=2.4.5 <2.6.1 depends on intl ^0.16.0 and flutter_form_builder 5.0.0 depends on intl ^0.17.0, if validators ^2.0.1 and flutter_form_builder 5.0.0 then vin_decoder 0.1.3 or basic_utils ^2.6.1.
> 
> And because flutter_form_builder 5.0.0 depends on validators ^2.0.1 and vin_decoder 0.1.3 depends on basic_utils ^2.6.3, flutter_form_builder 5.0.0 requires basic_utils ^2.6.1.
> And because internet_connection_checker is incompatible with basic_utils >=2.6.1 <3.0.0-nullsafety.0 (1), internet_connection_checker is incompatible with flutter_form_builder 5.0.0.
> 
> And because no versions of flutter_form_builder match >5.0.0 <6.0.0, internet_connection_checker is incompatible with flutter_form_builder ^5.0.0.
> So, because test_app depends on both flutter_form_builder ^5.0.0 and internet_connection_checker ^0.0.1, version solving failed.

I'm using Channel stable, 2.0.1

**Comment by RounakTadvi** [comment]
It seems your other dependencies depend on crypto ^2.1.5 whereas universal_io depends on ^3.0.0.

**Comment by hectorAguero** [comment]
As I said on the original PR, universal_io have to many dependencies.

Why not use https://pub.dev/packages/universal_platform, is a more lighweight solution.

**Comment by RounakTadvi** [comment]
The latest version of the package does not uses universal_io anymore, you can check it out and if you face an issue feel free to open a new issue, closing this issue since it's quite stale and the universal_io is removed as a dependency.
